Add box drawing support
fyne-io/terminal pull request #35
Opened 2023-08-31 11:05 UTC by mgazza

2023-09-02 12:47 UTC, andydotxyz commented
This looks really cool thanks. But like the other it has conflicts that need resolved before its tests can run.

2023-09-09 08:01 UTC, andydotxyz commented
Some of the added tests are failing as you can see in the actions report...

2023-09-11 16:35 UTC, mgazza commented
OK thats now sorted. I failed when rebasing

2023-09-12 09:42 UTC, andydotxyz requested changes
Please note failing static check reporting missing docs

2023-09-12 09:47 UTC, andydotxyz commented
Seems to work well btw, thanks for this - just get `staticcheck` passing and we're good.

2023-09-13 15:15 UTC, Jacalz commented on output.go
> +func handleShitIn(t *Terminal) {
Should these really contain "shit"?

2023-09-13 16:38 UTC, andydotxyz approved these changes
Thanks!

2023-09-13 16:38 UTC, merged